blank_issues_enabled: false
contact_links:
  - name: Onboarding and agent guidance
    url: https://github.com/baddiehustleai-star/jubilant-happiness/blob/main/.github/COPILOT_CODING_AGENT.md
    about: Read this first if you're contributing or using an automated agent.
